version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo "Installing Maven..."
      - apt-get update
      - apt-get install -y maven
  build:
    commands:
      - echo "Building Java Lambda function..."
      - mvn clean install -P prd
  post_build:
    commands:
      - echo "Zipping deployment package..."
      - cp target/ru-scraper-3.1.3-aws.jar ru-scraper.zip

      - echo "Updating Lambda Function (Bot)..."
      - aws lambda update-function-code --function-name ru-scraper-bot --zip-file fileb://ru-scraper.zip --region sa-east-1

      - echo "Updating Lambda Function (Pol)..."
      - aws lambda update-function-code --function-name ru-scraper-pol --zip-file fileb://ru-scraper.zip --region sa-east-1

      - echo "Updating Lambda Function (Cen)..."
      - aws lambda update-function-code --function-name ru-scraper-cen --zip-file fileb://ru-scraper.zip --region sa-east-1

      - echo "Updating Lambda Function (Agr)..."
      - aws lambda update-function-code --function-name ru-scraper-agr --zip-file fileb://ru-scraper.zip --region sa-east-1

      - echo "Finished buildspec process"
